on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASEURL}}
    permissions:
          contents: 'read'
          id-token: 'write'
 
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build
        run: ./scripts/buildprod.sh

      - name: Install goose
        run: go install go install github.com/pressly/goose/v3/cmd/goose@latest
    
      - name: Migration
        run: ./scripts/migrateup.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud builds submit --tag us-central1-docker.pkg.dev/notely-464002/notely-ar-repo/notely:latest .'

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-464002/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-464002 --max-instances=4
